### ISSUE TITLE
It always assigns a service

### ISSUE THREAD

**Issue by PHOLAN** [fgilde/GptInvoke#1]
A simple command such as: My name is Philip
Results in invoking the alarm clock service.

How can this be prevented?

**Comment by fgilde** [comment]
Yes if you're using gpt-4 as model it works very very well. But for sure gpt 4 is in preview and not everybody has access. In gpt 3 you need to check more on your implementation side. Like are all parameters really filled and convertable to required type

**Comment by fgilde** [comment]
Now its much better I changed small things, but as already said with GPT-4 you shouldn have problems

**Comment by PHOLAN** [comment]
Thank you!

Still waiting to get access to GPT4.

Regards,

Philip
